#postgres.crw8g0kciaek.us-east-1.rds.amazonaws.com


version: 0.2

env:
  variables:
    REGION: "us-east-1"
    REPO_NAME: "kxc-simple-api"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências..."
      - sudo apt-get update -y
      - echo "Instalando dependências..."
      - sudo apt-get install -y wget gpg apt-transport-https
      - echo "Adicionando repositório oficial da HashiCorp..."
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - echo "Atualizando lista de pacotes com o repositório da HashiCorp..."
      - sudo apt-get update -y
      - echo "Instalando Terraform..."
      - sudo apt-get install -y terraform

  pre_build:
    commands:
      - cd terraform
      - terraform init
      - terraform plan 
      - terraform apply -auto-approve
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851725492449.dkr.ecr.us-east-1.amazonaws.com
      - echo "Obtendo o endpoint do RDS..."
      - export DB_HOST=$(aws rds describe-db-instances --db-instance-identifier postgres --query "DBInstances[0].Endpoint.Address" --output text --region $REGION)

  build:
    commands:
      - echo "Substituindo o valor de DB_HOST no Dockerfile..."
      - sed -i "s/DB_HOST_VALUE/$DB_HOST/g" Dockerfile
      - echo "Construindo a imagem Docker..."
      - docker build -t $REPO_NAME .
      - echo "Marcando a imagem para envio ao ECR..."
      - docker tag $REPO_NAME:latest 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest

  post_build:
    commands:
      - echo "Enviando a imagem para o ECR..."
      - docker push 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest
      - echo "Gerando o arquivo imagedefinitions.json..."
      - echo '[{"name":"kxc-simple-api","imageUri":"851725492449.dkr.ecr.'$REGION'.amazonaws.com/'$REPO_NAME':latest"}]' > imagedefinitions.json
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - "**/*"