version: 0.2

env:
  variables:
    REGION: "us-east-1"
    REPO_NAME: "kxc-simple-api"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências..."
      - yum install -y unzip
      - curl -LO https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
      - unzip terraform_1.5.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - echo "Inicializando o Terraform..."
      - terraform init
      - echo "Aplicando a infraestrutura..."
      - terraform apply -auto-approve

  pre_build:
    commands:
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 851725492449.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Obtendo o endpoint do RDS..."
      - export DB_HOST=$(aws rds describe-db-instances --db-instance-identifier postgres --query "DBInstances[0].Endpoint.Address" --output text --region $REGION)
      - echo "Substituindo o valor de DB_HOST no Dockerfile..."
      - sed -i "s/DB_HOST_VALUE/$DB_HOST/g" Dockerfile
      - echo "Construindo a imagem Docker..."
      - docker build -t $REPO_NAME .
      - echo "Marcando a imagem para envio ao ECR..."
      - docker tag $REPO_NAME:latest 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest

  post_build:
    commands:
      - echo "Enviando a imagem para o ECR..."
      - docker push 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest
      - echo "Gerando o arquivo imagedefinitions.json..."
      - echo '[{"name":"kxc-simple-api","imageUri":"851725492449.dkr.ecr.'$REGION'.amazonaws.com/'$REPO_NAME':latest"}]' > imagedefinitions.json
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - "**/*"