version: 0.2

env:
  variables:
    REGION: "us-east-1"
    REPO_NAME: "kxc-simple-api"

phases:
  install:
    runtime-versions:
      docker: 18.15.0
    commands:
      - echo "Instalando dependências..."

  pre_build:
    commands:
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 851725492449.dkr.ecr.$REGION.amazonaws.com
      - echo "Obtendo o endpoint do RDS..."
      - export DB_HOST=$(aws rds describe-db-instances --db-instance-identifier postgres --query "DBInstances[0].Endpoint.Address" --output text --region $REGION)
      - echo "Endpoint do RDS: $DB_HOST"

  build:
    commands:
      - echo "Substituindo o valor de DB_HOST no Dockerfile..."
      - sed -i "s|ENV DB_HOST=\"\"|ENV DB_HOST=\"$DB_HOST\"|g" Dockerfile
      - echo "Construindo a imagem Docker..."
      - docker build -t $REPO_NAME .
      - echo "Marcando a imagem para envio ao ECR..."
      - docker tag $REPO_NAME:latest 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest

  post_build:
    commands:
      - echo "Enviando a imagem para o ECR..."
      - docker push 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - "**/*"