version: 0.2

env:
  variables:
    REGION: "us-east-1"
    REPO_NAME: "kxc-simple-api"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências..."
      - sudo apt-get update
      - sudo apt-get install -y wget gpg apt-transport-https
      - wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo sudo apt update
      - sudo apt install terraform

  build:
    commands:
      - echo "Inicializando o Terraform..."
      - terraform init
      - echo "Aplicando a infraestrutura..."
      - terraform apply -auto-approve
      - echo "Substituindo o valor de DB_HOST no Dockerfile..."
      - export DB_HOST=$(aws rds describe-db-instances --db-instance-identifier postgres --query "DBInstances[0].Endpoint.Address" --output text --region $REGION)
      - sed -i "s/DB_HOST_VALUE/$DB_HOST/g" Dockerfile
      - echo "Construindo a imagem Docker..."
      - docker build -t $REPO_NAME .
      - echo "Marcando a imagem para envio ao ECR..."
      - docker tag $REPO_NAME:latest 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest

  post_build:
    commands:
      - echo "Enviando a imagem para o ECR..."
      - docker push 851725492449.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest
      - echo "Gerando o arquivo imagedefinitions.json..."
      - echo '[{"name":"kxc-simple-api","imageUri":"851725492449.dkr.ecr.'$REGION'.amazonaws.com/'$REPO_NAME':latest"}]' > imagedefinitions.json
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - "**/*"